### ISSUE TITLE
problems in methplotlib 0.13.0

### ISSUE THREAD

**Issue by Coracollar** [wdecoster/methplotlib#20]
Hi, I have installed methplotlib and tried the example and works.
Now I have tried the simplest command with my data:
$ methplotlib -m chr10_methylation_calls.tsv chr10_methylation_frequency_chr10.tsv -n calls frequencies -w chr10:5,525,542-5,543,028

And obtained the following error

Traceback (most recent call last):
  File "/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/series.py", line 1014, in __setitem__
    self._set_with_engine(key, value)
  File "/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/series.py", line 1054, in _set_with_engine
    self.index._engine.set_value(values, key, value)
  File "pandas/_libs/index.pyx", line 96, in pandas._libs.index.IndexEngine.set_value
  File "pandas/_libs/index.pyx", line 106, in pandas._libs.index.IndexEngine.set_value
  File "pandas/_libs/index.pyx", line 116, in pandas._libs.index.IndexEngine.get_loc
TypeError: '605      True
621      True
637     False
653      True
668      True
        ...  
1597     True
1615     True
1633     True
1651     True
1669     True
Name: log_lik_ratio, Length: 1685, dtype: bool' is an invalid key

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/coracollar/anaconda3/envs/methplot/bin/methplotlib", line 10, in <module>
    sys.exit(main())
  File "/home/coracollar/anaconda3/envs/methplot/lib/python3.7/site-packages/methplotlib/methplotlib.py", line 34, in main
    dotsize=args.dotsize
  File "/home/coracollar/anaconda3/envs/methplot/lib/python3.7/site-packages/methplotlib/methplotlib.py", line 51, in meth_browser
    meth_traces = plots.methylation(meth_data, dotsize=dotsize)
  File "/home/coracollar/anaconda3/envs/methplot/lib/python3.7/site-packages/methplotlib/plots.py", line 107, in methylation
    dotsize=dotsize)
  File "/home/coracollar/anaconda3/envs/methplot/lib/python3.7/site-packages/methplotlib/plots.py", line 167, in make_per_read_meth_traces_llr
    table.loc[:, "llr_scaled"] = rescale_log_likelihood_ratio(table["log_lik_ratio"].copy())
  File "/home/coracollar/anaconda3/envs/methplot/lib/python3.7/site-packages/methplotlib/plots.py", line 253, in rescale_log_likelihood_ratio
    llr[llr > 0] = scaler.fit_transform(llr[llr > 0].values.reshape(-1, 1))
  File "/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/series.py", line 1037, in __setitem__
    self._where(~key, value, inplace=True)
  File "/home/coracollar/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 8727, in _where
    new_other[icond] = other
TypeError: NumPy boolean array indexing assignment requires a 0 or 1-dimensional input, input has 2 dimensions

**Comment by wdecoster** [comment]
I  believe I fixed that problem a few days ago, could you try updating to v0.13.1?
(for future reference https://github.com/wdecoster/methplotlib/commit/c8bc20c2c5be6325fac275f154cb4c8e6b57223b)

Thanks,
Wouter

**Comment by Coracollar** [comment]
Hi!
Yes it worked!!! Future reference for what?

Thanks,
Cora

**Comment by wdecoster** [comment]
Good to hear that. 
Oh a future reference for myself, mainly, if I have to figure this bug out again I can find which code I changed.

**Comment by Coracollar** [comment]
I've shared an item with you:

chr10_methylation_calls.tsv.gz
https://drive.google.com/file/d/1vkxX7_SA_LdXF-2FXZA54LPtfRubbyTV/view?usp=sharing&invite=CPmDj4kJ&ts=5ecc9f53

It's not an attachment -- it's stored online. To open this item, just click  
the link above.

**Comment by wdecoster** [comment]
That link doesn't seem to work for me.

**Comment by Coracollar** [comment]
https://drive.google.com/file/d/1vkxX7_SA_LdXF-2FXZA54LPtfRubbyTV/view?usp=sharing <https://drive.google.com/file/d/1vkxX7_SA_LdXF-2FXZA54LPtfRubbyTV/view?usp=sharing>

Does this one work?
