### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by tnn111** [wdecoster/methplotlib#34]
I'm trying to run methplotlib with the following command:

methplotlib -m mod_mappings.sorted.bam -n Run10 -w tig00000001 -f ../Run10_contigs.fasta -o Run10.out 2> Run10.log

and I get the following error:

2021-06-30 18:27:57,790 methplotlib 0.19.0 started.
2021-06-30 18:27:57,790 Python version is: 3.6.13 | packaged by conda-forge | (default, Feb 19 2021, 05:36:01)  [GCC 9.3.0]
2021-06-30 18:27:57,790 Arguments are: Namespace(bed=None, binary=False, dotsize=4, example=False, fasta='../Run10_contigs.fasta', gtf=None, methylation=['mod_mappings.sorted.bam'], minqual=20, names=['Run10'], outfile='Run10.out', qcfile=None, simplify=False, smooth=5, split=False, static=None, store=False, window='tig00000001')
2021-06-30 18:27:57,791 Processing tig00000001_0_965899
2021-06-30 18:27:57,792 File mod_mappings.sorted.bam is of type bam
2021-06-30 18:28:10,057 Error processing mod_mappings.sorted.bam.
2021-06-30 18:28:10,057 local variable 'refpos' referenced before assignment
Traceback (most recent call last):
  File "/home/torben/opt/anaconda3/envs/megalodon/lib/python3.6/site-packages/methplotlib/import_methylation.py", line 54, in read_mods
    return parse_cram(filename, file_type, name, window)
  File "/home/torben/opt/anaconda3/envs/megalodon/lib/python3.6/site-packages/methplotlib/import_methylation.py", line 213, in parse_cram
    mod_positions = get_modified_reference_positions(read)
  File "/home/torben/opt/anaconda3/envs/megalodon/lib/python3.6/site-packages/methplotlib/import_methylation.py", line 278, in get_modified_reference_positions
    refpos[modified_bases],  # pos
UnboundLocalError: local variable 'refpos' referenced before assignment

Any thoughts on what is causing it? I am using Megalodon to generate the BAM file.

**Comment by wdecoster** [comment]
Yes, that is definitely a bug. Luckily enough I have already fixed it, and now pushed a new version (v0.20.0) to be installed through pip.
Unfortunately, I don't have the time to test this in-depth, so I'd like to pre-emptively apologize if you encounter further issues - please let me know and I'd be happy to help.

Cheers,
Wouter
