### ISSUE TITLE
Python import issue

### ISSUE THREAD

**Issue by Eric-CH-Chen** [wdecoster/methplotlib#38]
Hi, I ran into a weird python import issue, tested with python 3.8.12 and python 3.6.13.

CMD:
`methplotlib -m Tf-NS-R1_remora_fast_5hmc_5mC_CG_modified_bases.sorted.bam -n Tf-NS-R1 -w contig_3:100000-200000 -f /data/eric/NanoporeAssemblies/ref/Tf_reference.fasta`

Error:
```
Traceback (most recent call last):
  File "/home/eric/miniconda3/envs/py3.6/bin/methplotlib", line 8, in <module>
    sys.exit(main())
  File "/home/eric/miniconda3/envs/py3.6/lib/python3.6/site-packages/methplotlib/methplotlib.py", line 36, in main
    minqual=args.minqual,  # only for input in bam/cram format
  File "/home/eric/miniconda3/envs/py3.6/lib/python3.6/site-packages/methplotlib/methplotlib.py", line 63, in meth_browser
    annotation=bool(bed or gtf))
  File "/home/eric/miniconda3/envs/py3.6/lib/python3.6/site-packages/methplotlib/utils.py", line 250, in create_subplots
    return plotly.subplots.make_subplots(
AttributeError: module 'plotly' has no attribute 'subplots'
```

I was able to get past the issue by adding `import plotly.subplots` to `utils.py`, after which the rest of the program finished without any issue.

**Comment by wdecoster** [comment]
Thanks for the report and the potential solution! Which version of plotly do you have?

**Comment by Eric-CH-Chen** [comment]
No worries!
Via `pip list`, they are both version 5.8.0 in my two environments.

**Comment by YingziZhang-github** [comment]
Hi,
I met with a python import issue also. Would you please help look into it?

CMD:
`(base) ➜  ~ /Users/zhany0s/miniconda3/bin/methplotlib`

Error:
```
Traceback (most recent call last):
  File "/Users/zhany0s/miniconda3/bin/methplotlib", line 5, in <module>
    from methplotlib.methplotlib import main
  File "/Users/zhany0s/miniconda3/lib/python3.7/site-packages/methplotlib/methplotlib.py", line 1, in <module>
    import methplotlib.plots as plots
  File "/Users/zhany0s/miniconda3/lib/python3.7/site-packages/methplotlib/plots.py", line 2, in <module>
    from methplotlib.annotation import parse_annotation, parse_bed
  File "/Users/zhany0s/miniconda3/lib/python3.7/site-packages/methplotlib/annotation.py", line 2, in <module>
    import pyranges as pr
  File "/Users/zhany0s/miniconda3/lib/python3.7/site-packages/pyranges/__init__.py", line 137, in <module>
    import pyranges.genomicfeatures as gf
  File "/Users/zhany0s/miniconda3/lib/python3.7/site-packages/pyranges/genomicfeatures.py", line 7, in <module>
    from sorted_nearest.src.introns import find_introns
  File "/Users/zhany0s/miniconda3/lib/python3.7/site-packages/sorted_nearest/__init__.py", line 7, in <module>
    from sorted_nearest.src.k_nearest_ties import get_all_ties, get_different_ties
ImportError: cannot import name 'get_all_ties' from 'sorted_nearest.src.k_nearest_ties' (/Users/zhany0s/miniconda3/lib/python3.7/site-packages/sorted_nearest/src/k_nearest_ties.cpython-37m-darwin.so)
```
Thank you very much.

**Comment by wdecoster** [comment]
Did you install with pip or conda? What is the version of your `sorted_nearest` module?
